ss220-space/TerraGov-Marine-Corps

- code/__DEFINES/typeids.dm
- code/__HELPERS/text.dm
- code/modules/admin/SDQL2/SDQL_2_wrappers.dm
- code/modules/client/preferences_ui.dm
- code/modules/instruments/songs/editor.dm
- code/modules/instruments/songs/play_legacy.dm
- code/modules/instruments/songs/play_synthesized.dm
- code/modules/keybindings/bindings_client.dm
Биндить хоткеи теперь можно на русской раскладке (бинд автоматически преобразуется в аналогичный символ на английской раскладке)
Вернул некоторые не _char функции на место (туда, где _char не нужен)
> Tweak: keybinds accept ru symbols + small reverts

- code/__HELPERS/text.dm
Ввод имени теперь обрабатывается как надо
> Fix: reject_bad_name() now works correctly

- code/controllers/subsystem/autofire.dm
Немного опциональной дебаг информации для автофаера, пытаемся узнать, почему не работает
> Tweak: Optional debug info collecting for automated fire SS

- code/controllers/subsystem/autofire.dm
Пробуем исправлять ломающуюся автострельбу
> Tweak: removing INVOKE_ASYNC from Automated Fire SS

- code/controllers/subsystem/autofire.dm
- code/datums/components/autofire.dm
Выяснили, что видимо проблема где-то в process_shot()
> Tweak: Collect more debug info

- code/datums/components/autofire.dm
Выяснили, что видимо проблема где-то в process_shot() и заменили пробелы на табы
> Fix: changed spaces to tabs

- code/controllers/subsystem/autofire.dm
Prayge на то что я правильно понял суть бага и это поможет
> Fix: possible fix for broken autofiring

- interface/skin.dmf
Изменил шрифт на тот, в котором буква Ё будет отображаться корректно
> Fix: letter "Ё" now displays correctly (#11)

- _maps/map_files/Talos/TGS_Talos.dmm
:cl:
fix: Fixes a few issues on the TGS Talos
/:cl:
> TGS_Talos_Fix

- _maps/map_files/Talos/TGS_Talos.dmm
:cl:
add: the captain's cabin, and the briefing room receive a fax machine.
fix: removal of unnecessary items (Wall lockers o2 and double APCs)
balance: replaced the Laser Beam in the pilot with a GAU-21 30mm Cannon. Small changes in pilot's initial arsenal.
balance: medbay gets an extra doctor's locker, which has a surgical kit. 
balance: removing some items from the ship that may have upset the balance compared to other maps (200 metal box and others)
/:cl:
> TGS_Talos_Fix_v1.1

- code/__HELPERS/text.dm
Добавляет опцию для принятия кириллицы в имени, отключенную по-умолчанию
:cl:
code: separate reject_bad_name option for cyrillic
/:cl:
> Feat: separate reject_bad_name option for cyrillic

- _maps/map_files/Talos/TGS_Talos.dmm
:cl:
add: RO got Overwatch console
add: Cargo got 2 supply vendors (Armor and clothing)
add: SO got 2 additional Crew monitoring consoles
add: Some areas got holopad
fix: Replaced erroneous admin walls on deck 2
/:cl:
> TGS_Talos_Fix_v1.2

- _maps/map_files/Talos/TGS_Talos.dmm
:cl:
add: CL stamp to his office.
add: additional regents and botanicals for the cook.
add: additional beaker with biomass for cloning.
add: bridge receives fax.
fix: medbay access is set up correctly.
fix: correction of some items on the map
feat: testing "stairway" ladders, replacing the standard vertical ones.
/:cl:
> Feat: update ship TGS Talos v1.3

- code/modules/mob/living/carbon/xenomorph/evolution.dm
- code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
Абуз лярво-взрослялки пофикшен, примордиалы нельзя купить, пока не будут открыты ставни
> Reworked xeno_upgrade section

- code/modules/mob/living/carbon/xenomorph/evolution.dm
- code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Офы не принимают мой ПР уже больше 2 недель. Суть ПРа в том, что починена система деволва и эволва. Я допустил в прод-версии билда, что можно регреснуть из эншента в примо предыдущей касты. Пофиксил.
> feat: Aliens can't regress to primo from ancient

- code/datums/gamemodes/distress.dm
- code/datums/gamemodes/nuclear_war.dm
Уменьшает разницу скорости спавна ксеносов на нюк варе и дистрессе.
А-состав считает что это хорошо.
:cl:
balance: Distress spawn rate 1 -> 1.2
balance: Nuclear war spawn rate 2.5 -> 2
/:cl:
> Скорость спавна ксеносов

- code/datums/jobs/job/job_exp.dm
- code/datums/jobs/job/shipside.dm
Фикс врремени на ФК, и фикс кода оффов на отображение времени наигрыша
фикс
:cl:
fix: timelocks
/:cl:
> Tracked playtime fixes

- code/game/objects/machinery/vending/marine_vending.dm
- code/modules/projectiles/ammo_datums.dm
- code/modules/projectiles/guns/smgs.dm
- code/modules/projectiles/magazines/misc.dm
- code/modules/projectiles/magazines/smgs.dm
- code/modules/reqs/supplypacks.dm
Обновление вектора с учетом обратной связи.
:cl:
balance: Vector is auto-only
balance: Cargo cost down to 20
balance: Sunder per second 5->4
balance: Vector unwielded nerf
fix: Ammo mags are larger by weight
fix: Vector to valhalla
/:cl:
> Vector Update

- ss220/code/RU_items.dm
Тесты показали что алебарда+трамадол сильно имбовее чем кажется. Нерф.
Урон 60/135 -> 50/90
Убраны бамп атаки (это очень важно)
Скорость атаки повышена 12->10 (у меча 7)
> VALHALA nerf

- ss220/code/RU_items.dm
Цена валибарды повышена до 40.
Можно плавить.
> Val-hal-a balance patch

- code/controllers/subsystem/job.dm
Добавляет проверку наигранного времени на раундстартовый выбор роли.
> Roundstart timelock checks

- code/__DEFINES/jobs.dm
- code/datums/gamemodes/distress.dm
- code/datums/jobs/job/survivor.dm
Добавляет слоты сурвов на Дистресс и Нюку. 3 слота. Можно играть если есть 300ч наиграно живым.
> Survivors jobs and playtime

- code/datums/components/harvester.dm
- ss220/code/RU_items.dm
Трамадол 60% урона -> 20% + 20 урона
> Trama rebalance

- code/datums/gamemodes/distress.dm
- code/datums/jobs/job/marines.dm
- code/datums/jobs/job/survivor.dm
- code/datums/jobs/job/xenomorph.dm
- code/datums/skills.dm
По умолчанию есть только 1 слот сурва. Потом за каждые 5 ксеносов дается еще один слот. Королева идет за 3 ксеноса. Да, сурвы могут появиться в середине раунда.
Сурвы так же теперь дают лярва поинты как обычный морпех (до этого сурвы не давали поинты, и ксено было меньше)
> Survivor rebalance and points system

- _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
- _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
* Удалены турели с одной из планетарных карт.
* Исправлено появление объекта на одной из карт.
> Removing Turrets From The Prison Map

- code/modules/reagents/reactions/medical.dm
:cl:
balance: rebalanced something
/:cl:
> Revert "Hyro, rye and synap now have lemoline in their recipes"

- code/modules/projectiles/guns/pistols.dm
- code/modules/projectiles/magazines/pistols.dm
Больше патронов, автоматический огонь, стрельба с одной руки.
Теперь у пистолета те статы, которые задумывались изначально.
> SP-13 (Calico) buff

- code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
- Урон в ближнем бою на снижен на 2 во всех стадиях взросления
- Здоровье увеличено на 25 во всех стадиях взросления
- Броня от пуль, огня, ближнего боя и лазеров увеличена на 10 во всех стадиях взросления
- Добавлена защита от взрывов. 20 на янг и матюре, 30 на элдере, эншенте и примо
> Твики дефайлера

- code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
- code/modules/projectiles/ammo_datums.dm
Регенерация плазмы на всех стадиях взросления увеличена на 5
Запас плазмы на всех взросления стадиях увеличен на 50
> Баффы сента

- code/modules/mob/living/carbon/xenomorph/abilities.dm
- code/modules/mob/living/living_verbs.dm
Ложиться и вставать можно даже в стаггере.
Буллинг нубо ксен дробовиками и репитерами это грустно :'(
> Stagger resting

- code/modules/clothing/modular_armor/modular.dm
Синты снова могут носить флэк джекет с модулями, ура.
Реверт пра Эльзы, усложнивший жизнь синтетикам.
Прошло авоут. https://discord.com/channels/617003227182792704/915500990931828736/1010507599399096372
:cl:
qol: made something easier to use
/:cl:
> Revert "Fix flak jacket accepting modules"

- code/game/objects/items/reagent_containers/glass/bottle.dm
Увеличивает количество с 5 нанитов в банке на 10
Прошло фулл путь из предложки до авоута и пролетело авоут.
:cl:
tweak: increase nanites bottle capacity from 5 to 10
/:cl:
> Tweak: increase nanites bottle capacity from 5 to 10

- code/modules/clothing/modular_armor/modular.dm
Не смотря на то, что реверт сделан, флек джекет до сих пор не принимает модули. Значит просто добавим в код флек джекету модули, взятые с ксеноаутена.
Теперь флек джекет точно может носить модули.
Прошло авоут. https://discord.com/channels/617003227182792704/915500990931828736/1010507599399096372
:cl:
fix: allowed attachments on flak jacket 
/:cl:
> Fix: allow attachments on flak jacket 

- code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
Reverts pr
Прошло авоут. https://discord.com/channels/617003227182792704/915500990931828736/1022888516390228030
:cl:
balance: carrier can panic drop at any percent of his hp
/:cl:
> revert "Carrier panic drop change"

- _maps/map_files/Barrenquilla_Mining/Barrenquilla_Mining_Facility.dmm
Так как оффы давно удалил Барраквиллу из ротации, её актуализацией RuTGMC придется заниматься вручную.
Добавил точки спавна для режима Комбат Патруль. А также заменил неразрушимые стены по краям карты на их 3/4 версию, теперь у них есть спрайт.
Актуализация карты, находящейся в ротации.
:cl:
fix: fixed Barrenquilla
/:cl:
> Make spawn point for CP (and also fix fix_me walls)

- ss220/code/RU_items.dm
Фикс импортной брони для роботов
:cl:
fix: fixed import robot armor
/:cl:
> Robotic armor fix

- _maps/map_files/Talos/TGS_Talos.dmm
🆑
add: Добавлен мех и специализированная комната
add: Изменение комнаты химии, +2 химии для морпехов
fix: Убран двойной APC в комнате инженеров
fix: Правка стеклянных перегородок (изменение слоев, для однородности конструкции)
fix: Генераторы теперь не болтированы, при раундстарте
feat: Дополнительные пару стаков коробок для отдела снабжения
/🆑
> Feat: Update mainship TGS Talos v1.6
